### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by rugk** [nielse63/jquery.resizeend#8]
Seeing you totally [ignore your bots](https://github.com/nielse63/jquery.resizeend/pull/7) and let bots have talks with bots, I have to ask, is this still maintained?

**Comment by nielse63** [comment]
Yep, still maintained. I just need to make changes to some config files to get those failing Travis tests passing again, and then I’ll merge that GreenKeeper PR. I’m planning on doing that after the holiday weekend. 

Thanks for reaching out!
